### ISSUE TITLE
no attackid for http/s logging

### ISSUE THREAD

**Issue by t3chn0m4g3** [DinoTools/dionaea#1]
Hello PhiBo,
first of all thank you very much for your efforts to keep dionaea alive and healthy!

When using dionaea or dionaea-phibo I have the problem that I do not get any log entries for http/s sessions. Reviewing and comparing dionaea.log debug entries for successful written logs with the ones which fail quickly reveals 

[22012016 15:59:59] logsql dionaea/logsql.py:754-warning: no attackid for 1.2.3.4:443

for http/s connections.

Any clues or help is appreciated!

Cheers,
Marco.

**Comment by phibos** [comment]
Thanks for reporting this issue. I have to do some testing and will push a fix in a few days.

**Comment by phibos** [comment]
Incidents for new TLS connections are now reported and logged. Can you please verify that it works as you expected it.

**Comment by t3chn0m4g3** [comment]
Installed the latest nightly, confirming attackid's and log information as expected for HTTP & HTTPS.

Thanks for the super fast fix!

**Comment by phibos** [comment]
You're welcome.

Thanks for testing. I have closed the issue.
