### ISSUE TITLE
Dropping privileges to early

### ISSUE THREAD

**Issue by phibos** [DinoTools/dionaea#108]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

- master
- 0.6
- 0.5

##### CONFIGURATION

Provide user and group to drop privileges.

##### OS / ENVIRONMENT

 - Ubuntu 14.04
 - Ubuntu 16.04
 - Debian 8.0

##### SUMMARY

Dropping privileges to early or binding sockets too late.

##### STEPS TO REPRODUCE

See #99 for additional information.

##### EXPECTED RESULTS

Bind ports before privileges are dropped

##### ACTUAL RESULTS

Unable to bind if dropping privileges

**Comment by phibos** [comment]
After analysing the issue everything looks fine. The kernel headers have to be installed during the build process to drop privileges and still bind to a privileged port.

**Comment by NibeP** [comment]
Looks like there are no kernel headers available for the Docker Ubuntu 16.04 image.
