### ISSUE TITLE
Log file gets big too fast

### ISSUE THREAD

**Issue by DZKeeper** [DinoTools/dionaea#109]
##### ISSUE TYPE

 - Question

##### DIONAEA VERSION
Latest

##### CONFIGURATION
standard

##### OS / ENVIRONMENT
 - Ubuntu 14.04

##### SUMMARY
dionaea.log gets a few gig of data in under 24hrs. How can we reduce the amount of data logged tot hat file ? in dionaea.cfg there is a section called:

[logging]
default.filename=@LOCALESTATEDIR@/dionaea/dionaea.log
default.levels=all
default.domains=*

What are the levels options of logging ?

**Comment by alfonsocaponi** [comment]
Using "import logging" I guess "debug(), info(), warning(), error() and critical()".
https://docs.python.org/3/howto/logging.html

**Comment by phibos** [comment]
I have added some information how to use the log levels. Feel free to have a look at [Configuration/Logging](https://dionaea.readthedocs.io/en/latest/configuration.html#logging)

Feel free to reopen the issue if log levels are still unclear to you.
