### ISSUE TITLE
"sip dionaea/sip/__init__.py:63-debug: Cleanup" with sip service disabled

### ISSUE THREAD

**Issue by alfonsocaponi** [DinoTools/dionaea#110]
Hi, I'm using the latest release on Ubuntu 16.04.
Why do have I this warning "sip dionaea/sip/__init__.py:63-debug: Cleanup" into dionaea.log with the **only** smb service enabled? sip service is disabled.

# ls -la services-enabled/
total 8
drwxr-xr-x 2 root root 4096 Jun  5 10:21 .
drwxr-xr-x 6 root root 4096 Jun  8 21:02 ..
lrwxrwxrwx 1 root root   30 Jun  5 10:07 smb.yaml -> ../services-available/smb.yaml

thank you

**Comment by phibos** [comment]
The clean up task for the sip service is a global task. I will fix this issue soon.

**Comment by phibos** [comment]
Thanks for reporting the issue. It should be fixed in the latest master branch. Feel free to reopen or create a new issue if something is still not working as expected.
