### ISSUE TITLE
Dionaea MySQL "show databases"

### ISSUE THREAD

**Issue by azthec** [DinoTools/dionaea#129]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
```
./dionaea --version

Dionaea Version 0.6.0 
Compiled on Linux/x86_64 at Jul 24 2017 14:18:36 with gcc 5.4.0 20160609 
Started on ae0006e186d2 running Linux/x86_64 release 4.4.0-64-generic


Dionaea Version 0.6.0 
Compiled on Linux/x86_64 at Jul 24 2017 14:18:36 with gcc 5.4.0 20160609 
Started on ae0006e186d2 running Linux/x86_64 release 4.4.0-64-generic
```
(I pulled from master, not sure why its 0.6.0)

##### CONFIGURATION
Only changed lines in dionaea.cfg are:
```
service_configs=/opt/dionaea/etc/dionaea/services/mysql.yaml
ihandler_configs=/opt/dionaea/etc/dionaea/ihandlers/log_json.yaml
```
mysql.yaml is at default, I have tried with and without an actual database, if I have a database setup I can do "use database", and "SELECT * FROM table_name;" and these do work.
log_json.yaml is working and writing logs to a specified json file.

##### OS / ENVIRONMENT
 - Ubuntu 16.04

##### SUMMARY
It is possible this is a misconfiguration of the information_schema variable in the mysql.yaml config (which is set to the default :memory:), however, everything in the mysql works, for example "use psn", "SELECT * FROM table_name;", except for commands like "show databases", "show tables", "select database()", even though these queries are clearly coded in the mysql.py file at the source code.

##### EXPECTED RESULTS
Output of existing databases and tables, etc.

##### ACTUAL RESULTS
```
"Learn SQL!"
```

**Comment by phibos** [comment]
Thanks for reporting the issue. A fix has been merged into the master branch. For more information have a look at #145
