### ISSUE TITLE
Showing the numbers of attacks from all Dionaea droplets

### ISSUE THREAD

**Issue by ghost** [DinoTools/dionaea#132]
Two month ago I had problem with showing statistic from Dionaea attacks: https://github.com/DinoTools/dionaea/issues/117 This solution works very well but I am not satisfied with it. Every few days I have to restart the supervisorctl services because the Mongo consumes almost 8GB of RAM and my MHN website getting 504 error often. 

So I have to ask - is any another solution to integrate with Dionaea honeypots (except MHN project)? I just need to gather information on the number of attacks from all Dionaea honeypots.

**Comment by JBAnderson** [comment]
There is a configuration issue if MHN is taking up 8GB of RAM. My install has been cooking along for months with no issues. Check out this blog post and see if it gets you working correctly:
https://www.attacusatlas.com/how-to-set-up-dionaea-honeypot-with-modern-honey-network-and-slack-alerts/

That said, if you are just looking for numbers you could repurpose log_json or hpfeeds and roll your own solution. You could roll a simple simple Python or NodeJS server that listens for data from log_json or hpfeeds and processes that data however, for example. The blog post above has a NodeJS server template that might help you get started with processing data from log_json.

**Comment by br1877** [comment]
Your tutorial is great but it does not describe how to configure MHN server properly. I had use official instruction only. Everything working good for first few days but then, if the numer of attacks is above 100K, it works very slowly (my VPS config: 200GB HDD, 2x CPU, 8GB ram and now 99% RAM is unavailable).

The own little server to listen for data might be better, but too harder to make for me.

**Comment by fe7ch** [comment]
>Is possible to integrate Dionaea with Kibana or ELK or another Dashboard?

I guess it's possible if you enable json logging (incidents, if I remember its name correctly).

By the way, Kibana is a part of ELK. ELK stands for Elasticsearch, Logstash, Kibana.

**Comment by br1877** [comment]
Any tutorial, instruction?

**Comment by fe7ch** [comment]
I have it in plans, but not for the near future...

Basically, it's not hard. You need json log of dionaea events (var/dionaea/dionaea_incident.json). Then you config logstash to read this file and send events to elasticsearch (optionally, you can make additional changes there like geoip positioning, removing unused fields and so on). The last step is visualizing events in kibana.

A short tutorial on how to setup ELK stack you may read there: https://github.com/micheloosterhof/cowrie/tree/master/doc/elk  . Configs are designed for Cowrie honeypot, but you can read them to get an idea how it should look like.

**Comment by phibos** [comment]
Looks like multiple solutions have been provided in #134. Closing the issue.
