### ISSUE TITLE
HTTP handle post function crash

### ISSUE THREAD

**Issue by pavervier** [DinoTools/dionaea#135]
Just dropping this question/bug report by you guys. The function "handle_POST" crashes at line 603 when attempting to access a null pointer. The "if" statement at line 602 checks for "self.fp_tmp" is None, although it should probably check for "self.fp_tmp" is *not* None.

See if it makes sense.

https://github.com/DinoTools/dionaea/blob/02492e2b97326a5ebc032a35053e9cba4b48035e/modules/python/dionaea/http.py#L602
https://github.com/DinoTools/dionaea/blob/02492e2b97326a5ebc032a35053e9cba4b48035e/modules/python/dionaea/http.py#L603

**Comment by phibos** [comment]
Thanks for reporting the issue. It has been fixed and merged into the master branch.
