### ISSUE TITLE
Rotate logs?

### ISSUE THREAD

**Issue by Tigzy** [DinoTools/dionaea#136]
How can I rotate logs in the configuration?
After some time it fills up the disk.

**Comment by ixiss78** [comment]
Hi, I would advise you to use logrotate for this :)

**Comment by mcantoni** [comment]
http://dionaea.readthedocs.io/en/latest/old/configuration.html?highlight=rotate

**Comment by phibos** [comment]
The information is part of the old documentation and rotating might not work without a restart at the moment. Please have a look at #206. Documentation will be updated when issue #206 has been fixed.
