### ISSUE TITLE
Bistreams fill my HDD very quickly

### ISSUE THREAD

**Issue by Tigzy** [DinoTools/dionaea#156]
Is there a way to rotate them, as well as binaries? 
I have a script that upload binaries to another server so I don't need them to fill my HDD

I see the config section but didn't find any doc to tweak it

[processor.streamdumper]
name=streamdumper
config.path=/opt/dionaea/var/dionaea/bistreams/%Y-%m-%d/

**Comment by Aws0mus** [comment]
You can use something like this:

```
#!/bin/bash

#Clear bistream logs from dionaea every week
#It should run in a daily crontab

find /opt/dionaea/var/dionaea/bistreams/* -type f -mtime +7 -exec rm {}
find /opt/dionaea/var/dionaea/bistreams/* -type d -empty -delete
```

**Comment by phibos** [comment]
I have added a slightly modified version of the script provided by @Aws0mus to the new tips and tricks section. Thanks for answering the question.
