### ISSUE TITLE
[feature] Confgurable python sitelib

### ISSUE THREAD

**Issue by xambroz** [DinoTools/dionaea#164]
##### ISSUE TYPE
 - Feature Idea

##### DIONAEA VERSION
0.6.0 - commit d2efb76

##### CONFIGURATION
- compile time

##### OS / ENVIRONMENT
Fedora 27

##### SUMMARY
I am trying to pack dionaea as Fedora RPM package.
The build scripts are hardcoded with the unversioned python directory for the python site libraries.
It would be nice to have this set in a separate variable, which could be overriden externally from the commandline during the build time to control where the python scripts would go.
According the Fedora guidelines this should for example go to directory given by:
python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())" -> "/usr/lib/python3.6/site-packages"
instead of the $(pkglibdir)"/python/dionaea/$$i  => /opt/dionaea/lib/python/

##### EXPECTED RESULTS
I would expect to have variable PYTHON_SITELIB defined in the modules/python/dionaea/Makefile.am same way as you have it now:
PYTHON_SITELIB=$(pkglibdir)"/python"

Then during build time it could give me chance to do:
make install DESTDIR=%{buildroot} PYTHON_SITELIB=%{python3_sitelib} 

##### ACTUAL RESULTS
python path is now hardcoded in the modules/python/dionaea/Makefile.am

**Comment by xambroz** [comment]
Please consider merging the PR https://github.com/DinoTools/dionaea/pull/165

**Comment by phibos** [comment]
I think this is a good idea but the python package might not be usable if it is not loaded as a dionaea module.

**Comment by phibos** [comment]
Thanks for providing the patch. I have merged your PR.
