### ISSUE TITLE
Some code is hardcoded with the prefix /opt/dionaea

### ISSUE THREAD

**Issue by xambroz** [DinoTools/dionaea#168]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
0.6.0 - commit d2efb76

##### CONFIGURATION
Irrelevant 

##### OS / ENVIRONMENT
Fedora 27 

##### SUMMARY
Some code in the project is hard-coded with the prefix /opt/dionaea, while other code's prefix is configured by the "configure" script. This is inconsistent and can lead to missconfiguration.

##### STEPS TO REPRODUCE
grep -R "/opt/dionaea" *

##### EXPECTED RESULTS
The path "/opt/dionaea" should be present only in the automake defaults. All the rest should be regenerated from templates by "./configure --prefix=/something" and follow the settings from there or from the automake default prefix if executed just like "./configure"

##### ACTUAL RESULTS
Some files follow the "--prefix" settings, but some of the code is hardcoded with the /opt/dionaea.

**Comment by phibos** [comment]
Looks like all hard coded values in the source code have been removed during the migration from autotools to cmake. I'm closing the issue.

Please feel free to reopen or to create a new one if you find a hard coded ```/opt/dionaea```
