### ISSUE TITLE
Some scripts hardcoded with python version 3.2

### ISSUE THREAD

**Issue by xambroz** [DinoTools/dionaea#169]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
0.6.0 - commit d2efb76

##### CONFIGURATION
irrelevant

##### OS / ENVIRONMENT
Fedora 27

##### SUMMARY
Some of the scripts are hardcoded with the python version 3.2. This can cause problems on systems where this python version was already obsoleted.  I would recommend changing to the python3 only.

##### STEPS TO REPRODUCE
$ grep -R python3.2 *
debian/control:Build-Depends: debhelper (>= 5), pkg-config (>=0.22), libglib2.0-dev (>= 2.22.2), libcurl4-openssl-dev (>= 7.19.5), python3.2-dev (>= 3.2), cython (>= 0.14.2), libudns-dev (>= 0.0.9), libssl-dev (>= 0.9.8g), liblcfg (>= 0.2.0), libemu (>= 0.2.0), libev-dev (>= 4.0)
debian/control:Depends: libglib2.0-0 (>= 2.22.2), libcurl3 (>= 7.19.5), libpython3.2 (>= 3.2), libudns0 (>= 0.0.9), libssl0.9.8 (>= 0.9.8g), liblcfg (>= 0.2.0), libemu (>= 0.2.0), libev3 (>= 4.0)
doc/html/index.html:      --with-python=/opt/dionaea/bin/python3.2 \
m4/az_python.m4:    AC_PATH_PROG( PYTHON, python3.2, [], $1 )
modules/python/util/readlogsqltree.py:#!/opt/dionaea/bin/python3.2

##### EXPECTED RESULTS
I would expect that more generic and time sustainable python3 is used instead so it is possible to simply use the system-installed modern/patched python.

##### ACTUAL RESULTS
At least the m4/az_python.m4 and modules/python/util/readlogsqltree.py are referring to python3.2 and should refer to python3 instead.

**Comment by xambroz** [comment]
Please consider running:
sed -i -e 's|python3.2|python3|g;' \
    m4/az_python.m4 \
    doc/html/index.html \
    modules/python/util/readlogsqltree.py

**Comment by phibos** [comment]
Thanks for reporting the issue. It should have bin fixes in #190
