### ISSUE TITLE
Dozens of warnings during the generation of documentation

### ISSUE THREAD

**Issue by xambroz** [DinoTools/dionaea#170]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
0.6.0 - commit d2efb76

##### CONFIGURATION
build time

##### OS / ENVIRONMENT
Fedora 27

##### SUMMARY
when building the "html" documentation with sphinx-build it throws bunch of warnings. 

##### STEPS TO REPRODUCE
git clone https://github.com/DinoTools/dionaea
cd dionaea
cd doc
make html

##### EXPECTED RESULTS
It should quietly generate documentation

##### ACTUAL RESULTS
This list of warnings is generated:

/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/configuration.rst:118: WARNING: Unknown target name: "xmpp".
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/configuration.rst:119: WARNING: Unknown target name: "xmpp".
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:59: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:59: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:65: WARNING: Unexpected indentation.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:74: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:105: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:108: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:125: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:125: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:125: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:125: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:125: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:125: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:125: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:136: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:136: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:136: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:143: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:146: WARNING: Unexpected indentation.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:146: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:146: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:149: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:150: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:150: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:153: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:157: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:184: WARNING: Unexpected indentation.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:184: WARNING: Inline strong start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:184: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:184: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:184: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:184: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:184: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:184: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:205: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:215: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/seagfaults.rst:217: WARNING: Inline emphasis start-string without end-string.
/home/user1/rpmbuild/BUILD/dionaea-d2efb768e753a7f1ddca6dbf402548d741f33574/doc/source/old/utils.rst:36: WARNING: Unexpected indentation.

**Comment by phibos** [comment]
Thanks for your help. PR #211 should fix the warnings.
