### ISSUE TITLE
Replace autotools with cmake

### ISSUE THREAD

**Issue by phibos** [DinoTools/dionaea#172]
##### ISSUE TYPE

 - Feature Idea

##### DIONAEA VERSION

```
<= 0.7.0
```

##### OS / ENVIRONMENT

 - all

##### SUMMARY

Dionaea uses autotools as build system with a very old configuration. The m4 scripts are very hard to maintain and there are some unresolved bugs. I think it might be a good idea to migrate the build system from autotools to cmake to make it more flexible and easier to maintain.

Migrating to cmake should also make packaging much easier.

**Warning**: cmake is not a drop in replacement.

I have started with some initial task and it looks promising.

Release plan:
* 0.7.0 - introduce cmake, autools still the main build system
* 0.8.0 - cmake becomes the main build system, autotools as fallback
* 0.9.0 - remove autotools

**Comment by swobspace** [comment]
The migration to cmake seems not complete yet. I'm using the latest master from git and tried
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/dionaea ..
```
Dionaea seems running normal, but binding to interface didn't work (no error, just no listening ports with netstat -lnt). I switched back to autoconf + configure as mentioned in the documentation vor v0.7.0 and binding works at least with
```
listen.mode=manual
listen.addresses=<explicit ip>
```
System: current raspbian with Kernel 4.14.34-v7+ on Rasberry Pi 2B and kernel headers installed.

**Comment by phibos** [comment]
All changes have been merged into the master branch. Feel free to open a new issue if you find an issue with the new cmake build config.
