### ISSUE TITLE
dionaea doesn't call chdir before calling the chroot.

### ISSUE THREAD

**Issue by xambroz** [DinoTools/dionaea#176]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
Dionaea Version 0.6.0  (commit 1748f3b3936aa1da2d92500251ae8010fe181dfc)
Compiled on Linux/x86_64 at Apr  7 2018 00:24:14 with gcc 7.3.1 20180303 (Red Hat 7.3.1-5) 
Started on myhost running Linux/x86_64 release 4.15.12-301.fc27.x86_64
```

##### CONFIGURATION

irelevant

##### OS / ENVIRONMENT

- irelevant
- Fedora 27

##### SUMMARY

dionaea doesn't call chdir before calling the chroot. It was identified running the rpmlint on the binary package.

##### STEPS TO REPRODUCE

```
rpmlint rpmlint --info --verbose ~/rpmbuild/RPMS/x86_64/dionaea-0.6.0-4.20180326git1748f3b.fc27.x86_64.rpm
```

##### ACTUAL RESULTS

```
dionaea.x86_64: E: missing-call-to-chdir-with-chroot /usr/sbin/dionaea
This executable appears to call chroot without using chdir to change the
current directory. This is likely an error and permits an attacker to break
out of the chroot by using fchdir. While that's not always a security issue,
this has to be checked.

```

I believe the chdir should be called. Please consider merging the pull request 
https://github.com/DinoTools/dionaea/pull/175

**Comment by phibos** [comment]
Thanks for reporting the issue and providing a patch. The patch has been merged into the master branch and will be included in the next release.
