### ISSUE TITLE
when ppa package work on ubuntu 18?

### ISSUE THREAD

**Issue by jjjan** [DinoTools/dionaea#198]
Hello,
may i know when ppa package work on ubuntu 18?

**Comment by phibos** [comment]
There are currently no plans to update the existing packages for Ubuntu 14.04 or to make new packages for any other version of Ubuntu.

**Comment by phibos** [comment]
At the moment we recommend the build from source on Ubuntu or Debian and the docker image. If someone is willing to spend some time to build new packages feel free to contribute and open an PR.

Closing the issue for now.
