### ISSUE TITLE
the .gitignore contains also pattern for config.h.cmake

### ISSUE THREAD

**Issue by xambroz** [DinoTools/dionaea#199]
Hello,
the .gitignore contains also pattern config.* , which is matching also the source configuration file config.h.cmake. Changes to this file might not be tracked properly.
Please would it be possible to keep the config.h.cmake counted and not ignored?

Thank you
Michal Ambroz

**Comment by phibos** [comment]
Thanks for reporting the issues. I will fix this soon.
