### ISSUE TITLE
MySQL connection - all sql statements result in errors

### ISSUE THREAD

**Issue by t3chn0m4g3** [DinoTools/dionaea#2]
Hello PhiBo,

When using your dionaea nightly builds I have the problem that when connecting to tcp/3306 via mysql every sql statement results in an error. However with the dionaea-phibo builds everything works fine, though.

Any clues or help is appreciated!

Cheers,
Marco.

**Comment by phibos** [comment]
Thanks for reporting this issue. I will try to reproduce it.

**Comment by phibos** [comment]
The fix will be included in the next nightly builds in a few hours.

**Comment by t3chn0m4g3** [comment]
Works as advertised!

Thank you very much for the quick fix!
