### ISSUE TITLE
Unable to bind

### ISSUE THREAD

**Issue by cybercyto** [DinoTools/dionaea#205]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
Current

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
 - Ubuntu 16.04
 - Debian 9.0

##### SUMMARY
After compiling und starting ./dionaea -u nobody the following error occurs:

[31052018 19:41:44] connection /home/ihoerr/Downloads/dionaea/src/connection.c:218: Could not bind 192.168.44.20:23 (Permission denied)

I have installed the linux-headers under /usr/src. But nothing happens...

**Comment by phibos** [comment]
Can you provide some additional information please.
* Current = 0.6.0 or master?
* Build system autotools or cmake?
* Did you start dionaea with extended permissions e.g. as root or by using sudo?

**Comment by cybercyto** [comment]
Current = 0.6.0 or master?
A: I used git clone https://github.com/DinoTools/dionaea.git

Build system autotools or cmake?
A: I use the https://dionaea.readthedocs.io/en/latest/installation.html to install it from the source.

Did you start dionaea with extended permissions e.g. as root or by using sudo?
I start it with a normal user. If I start it with root, the error is not there. Also I tried this _setcap cap_net_bind_service=+ep dionaea_, but it did not help.

**Comment by phibos** [comment]
I'm sorry but I'm unable to reproduce the error.

I have used Ubuntu 16.04 inside a docker container and running dionaea as a normal user failed, because a process started by normal user is not allowed to bind to a privileged port.

After setting the capabilities you have mentioned everything worked as expected. 
```
setcap cap_net_bind_service=+ep /opt/dionaea/bin/dionaea
```

**Comment by phibos** [comment]
No response within 14 days, reported issue wasn't reproducible and configuration worked as expected in our tests.

Closing the issue. Please reopen the issue or create a new one if you still have issues.
