### ISSUE TITLE
Dionaea os fingerprinting

### ISSUE THREAD

**Issue by ahmedkhiar** [DinoTools/dionaea#216]
Hello all,

I deployed dionaea with smb service enabled, the problem I m facing is that with a simple nmap probe, it detect my real operating system which is linux, is there a way to change the fingerprint so that the nmap probe returns windows os instead of linux ?

Thank you.

**Comment by jaredfrees** [comment]
Changing the mac address on your machine can fix this.

**Comment by phibos** [comment]
Duplicate of #222. Closing the issue.
