### ISSUE TITLE
DIONAEA SMB and OS

### ISSUE THREAD

**Issue by ahmedkhiar** [DinoTools/dionaea#222]
hello everybody,

I dont understand something, we deploy dionaea on a linux machine and we run SMB on that machine, its some of a contradiction, smb in a linux machine, a simple nmap scan will show the service which is normally available on a windows machine, on a linux one ..

Can somebody enlighteen me ?

**Comment by phibos** [comment]
You can setup your honeypot in different ways. But I'm not going to explain every detail.

Here are some examples:

* Open as many ports as you can and try to capture automated attacks.
  * Your Windows Server might look like a Linux Server or the other way around
* Only start the services your server should provide and use a firewall to drop the rest
* ...

Just be creative. There is no best practice or something similar, it highly depends on what you are trying to achieve. You might just have a look at the servers around your honeypot and try to be as close as possible with your configuration.
