### ISSUE TITLE
How To Stop Dionaea on Ubuntu 16.04?

### ISSUE THREAD

**Issue by riupie** [DinoTools/dionaea#232]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### DIONAEA VERSION
Dionaea Version 0.8.0-17-g93d5bf9
Compiled on Linux/x86_64 at Aug 16 2018 22:07:56 with gcc 5.4.0 20160609
Started on ubuntu running Linux/x86_64 release 4.4.0-93-generic

##### OS / ENVIRONMENT

 - Ubuntu 16.04

##### SUMMARY
Like in title, just how? On Ubuntu 14.04 you could type command : service dionaea stop. How about Ubuntu 16.04?

**Comment by sereysethy** [comment]
How did you install it? Do you use `supervisor`?

**Comment by riupie** [comment]
I installed from source  like in documentation.  https://dionaea.readthedocs.io/en/latest/installation.html

**Comment by sereysethy** [comment]
If you follow the installation as per documentation, then I think it is not even started yet. When you make install, it just copied files to the `/opt/dionaea` folder. You can check with `ps -ef | grep dionaea` to see if the program started already?

**Comment by phibos** [comment]
dionaea can use a PID file to provide its current PID. Feel free to have a look at https://dionaea.readthedocs.io/en/latest/run.html .

**Comment by riupie** [comment]
@sereysethy i started the service via /opt/dionaea/etc/dionaea and i has been started.

**Comment by riupie** [comment]
@phibos so it means i could use kill command if wanna stop dionaea?

**Comment by NibeP** [comment]
You can use 
‘ps aux | grep dionaea’
‘kill -9 PROCESSID’

**Comment by riupie** [comment]
@NibeP after i used kill -9 PROCESSID, dionaea still exist when i saw with "ps aux | grep dionaea" command.

**Comment by NibeP** [comment]
@riupie To be sure: you have repaced "PROCESSID" with the actual Process ID of dionaea you saw with "ps aux | grep dionaea" ?

**Comment by riupie** [comment]
case closed. I used pkill command. Maybe we need command like-> dionaea start, dionaea stop in the next update?

**Comment by ahezza** [comment]
Hello, 
Try this if you installed Dionaea from source.
`nano /etc/systemd/system/dionaea.service`
Enter the following in this file:
```
[Unit]
Description=Dionaea
[Service]
WorkingDirectory=/opt/dionaea
ExecStart=/opt/dionaea/bin/dionaea
User=localuser
Group=localuser
Restart=always
[Install]
WantedBy=multi-user.target
```
Make sure you change the "localuser" variable to a user with sufficient permissions to run Dionaea.
Lastly, change the permissions on the file:
`chmod 755 /etc/systemd/system/dionaea.service `
Now you'll be able to run the service using:
`sudo systemctl start dionaea.service`
You can verify it's working by using:
`sudo systemctl status dionaea.service`
You will see output like the following if it's running successfully:
```
$ sudo systemctl status dionaea.service
● dionaea.service - Dionaea
   Loaded: loaded (/etc/systemd/system/dionaea.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-03-11 12:55:02 CET; 3s ago
 Main PID: 1579 (dionaea)
    Tasks: 4
   Memory: 27.0M
      CPU: 1.168s
   CGroup: /system.slice/dionaea.service
           ├─1579 /opt/dionaea/bin/dionaea
           └─1582 /opt/dionaea/bin/dionaea

Mar 11 12:55:02 vps658780 systemd[1]: Started Dionaea.
```

**Comment by riupie** [comment]
Wew, It's been a long time. I end up using supervisord in that time. But thanks!
