### ISSUE TITLE
Printer support (PCL/PJL)

### ISSUE THREAD

**Issue by michaelneu** [DinoTools/dionaea#245]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
I wrote a [printer honeypot](https://github.com/michaelneu/pjl-honeypot), which I could integrate into dionaea over the holiday season. Would you be interested in such a honeypot?

We're running honeypots in a university course to collect and analyze malware. From our stats, printers are by far not as attractive targets to attackers as e.g. SMB, but we still receive some prints since the rise of "printer advertising". By integrating my honeypot into dionaea, a wider audience would be able to receive and analyze "attacks" against printers by simply adjusting their dionaea config.

##### EXPECTED RESULTS
Receive prints not meant for the public (wrong printer setup), monitor attacks from e.g. PRET, or to get a laughter here and there, when somebody prints a page about "serpent people in New York" (most likely outcome).

**Comment by phibos** [comment]
I had the same idea a few years ago but didn't had the time to implement it. Please feel free to implement this feature for dionaea and create a merge request.

You can find additional information on how to in the documentation. [How to contribute](https://dionaea.readthedocs.io/en/latest/contributing.html)

**Comment by michaelneu** [comment]
I'm not sure if you received a notification after @dino-bot replied to the PR. Have you already found some time to look at #246 and are there any changes required to get it merged?

**Comment by phibos** [comment]
We should wait for #294

**Comment by phibos** [comment]
@michaelneu Thanks for contributing. I would be happy if you would like to maintain your code.
