### ISSUE TITLE
send json log via http

### ISSUE THREAD

**Issue by nassimabedi** [DinoTools/dionaea#248]
I want to send json log via http but I can not do this.
It logs in filename but I can not send log via http.

I use  Ubuntu 18.04 and did these steps:

-  add these lines to file `conf/dionaea.cfg.cmake`

 
```
 json.host=http://127.0.0.1:8080/
 json.levels=all
 json.domains=*
```
 
 
- and build it.

**Comment by phibos** [comment]
Can you please tell me where you found this feature in the documentation.

You might want to have a look at:

* https://dionaea.readthedocs.io/en/latest/ihandler/log_incident.html
* https://dionaea.readthedocs.io/en/latest/ihandler/log_json.html

**Comment by phibos** [comment]
No response within a year. Closing the issue. Please feel free to open a new issue if you have any question or idea.
