### ISSUE TITLE
IP inserted in wrong column

### ISSUE THREAD

**Issue by savamarius** [DinoTools/dionaea#25]
For some types of connection protocol (mirrorc and ftpdataliste) in sqlite database the source ip is inserted in remote_hostname column instead of remote_host column.

How to reproduce:
nmap -sV -T4 -F -O -p21,22,42,80,135,445,1443,3306, 1723, 5060, 5061,6667,50000 localhost

**Comment by phibos** [comment]
Thanks for reporting the issue. I was able to reproduce the bug and will fix it soon.

**Comment by savamarius** [comment]
Also to reproduce for ftpdataliste you should follow the next stepts:
ftp IP_DIONAEA
ANY PASSWORD
SOME COMMANDS

**Comment by phibos** [comment]
I have fixed the bug. Please reopen if there are any problems.
