### ISSUE TITLE
dionaea doesn't drop privileged groups before dropping to user doing setresuid (regression #177)

### ISSUE THREAD

**Issue by xambroz** [DinoTools/dionaea#255]
##### ISSUE TYPE
 - Bug Report - Security
##### DIONAEA VERSION
```
0.8.0
baf25d6d40db7018562e22c03b60b4f43317f206
```
##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Any/Github

##### SUMMARY
Issue #177 was supposed to be patched in 0.7.0, but the code was reverted before 0.8.0 release. As a result when dropping privileges from root to dionaea there is risk that the process might retain privileges of some of the supplemental groups root account is assigned to and dionaea unprivileged account should not have access to.

##### STEPS TO REPRODUCE
code review

##### EXPECTED RESULTS
Apply PR #178

**Comment by phibos** [comment]
I have reopened and merged the PR #178 again. Thanks for reporting and fixing the issue.
