### ISSUE TITLE
hpfeeds payload content

### ISSUE THREAD

**Issue by opliyal3** [DinoTools/dionaea#271]
I hava this contents in my mongoDB
but I have to know where is the payload content in my dionaea or can i found
maybe can I setting the payloads contents in my dionaea?

![image](https://user-images.githubusercontent.com/30455352/70607095-cb227200-1c38-11ea-9d60-808299f84415.png)

**Comment by phibos** [comment]
Please have a look at the hpfeeds ihandler. The payload is generate here https://github.com/DinoTools/dionaea/blob/df601896ab673ed9a26f119fa51d9c3c06429f33/modules/python/dionaea/hpfeeds.py#L330-L340

Is this what you are looking for?
