### ISSUE TITLE
Directory not exists "/root/dist/etc/* /opt/dionaea/etc/dionaea/ && \"

### ISSUE THREAD

**Issue by nabeelrashid** [DinoTools/dionaea#280]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
- dionaea 0.8.0

##### OS / ENVIRONMENT
 - Debian 8.0

##### SUMMARY
Directory not exists "/root/dist/etc/* /opt/dionaea/etc/dionaea/ && \"

##### STEPS TO REPRODUCE
docker build --rm -f "Dockerfile" -t dioneacdp:latest "."
-response 
Error in building building given Docker file
Directory not exists "/root/dist/etc/* /opt/dionaea/etc/dionaea/ && \"

**Comment by phibos** [comment]
Can you please provide your Dockerfile
