### ISSUE TITLE
Upon Hardening Dionaea

### ISSUE THREAD

**Issue by lemourios** [DinoTools/dionaea#283]
Feature Idea - Hardening Dionaea

Hi all,

I have downloaded and used dionaea provided by the T-pot suite.

My question is what can we do to harden the dionaea honeypot it-self.
I read in similar logs that we can customize the messages provided by various services.
However, this is not hardening. This was mostly for NMAP, to stop identifying Dionaea as a honeypot.

I wonder if we can customize Dionaea ports or services, or provide a list of connected users for the respective services. In addition, can in some patch any vulnerabilities in the versions of various services used via Dionaea?

If yes, how can we do that?

Any other hardening idea is welcome.

Thank you

**Comment by phibos** [comment]
You are addressing different topics in your question.

Hardening includes writing safer code, dropping privileges(you can already do this by providing a user and a group), run dionaea in a container, guard the process with AppArmor or SELinux and so on.

Customizing dionaea to make it more realistic is a different topic. Have a look at the module documentation to see what options are already available https://dionaea.readthedocs.io/en/latest/service . Feel free to provide provide code or ideas to add more customization features.

One of the main goals of dionaea is to reimplement a service or protocol as good as possible and to detect attacks by using libemu, external tools, statistics and so on. Therefore it is not recommended to add code to handle one single attack vector.

I hope this helps.

**Comment by phibos** [comment]
No response within a month. Looks like the issue has been solved. I'm closing the issue. Please feel free to open a new issue if you have any question or if you want to contribute to dionaea.
