### ISSUE TITLE
Dionaea in Kubernetes

### ISSUE THREAD

**Issue by Xsenonn** [DinoTools/dionaea#285]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### DIONAEA VERSION

```
Dionaea Version 0.8.0
```

##### OS / ENVIRONMENT

 - CentOS7 Container

##### SUMMARY

I'm trying to start Dionaea as a Pod in Kubernetes cluster. 
Pod itself starts properly as well as Service, but I can't access any of services hosted by Dionaea
(For example curl of <Service IP>:81 returns Connection refused. 
When trying to connect with ftp I also get Connection refused).
##### STEPS TO REPRODUCE

Install Minikube with MetalLB as LoadBalancing Solution. 
Configure MetalLB. 
Apply YAMLs from Gists.

Dionaea deployment:
https://gist.github.com/Xsenonn/94f417b58df943a6401232560dce8321

Dionaea LoadBalancer:
https://gist.github.com/Xsenonn/add4e19cebfc22b7d117d8c74a8c749e

Dionaea UDP LoadBalancer:
https://gist.github.com/Xsenonn/535a277bf24d76296247a26648700b89

##### EXPECTED RESULTS

Access to all services advertised by Dionaea.

##### ACTUAL RESULTS

No logs appear on any of pods. No services are available. 
Dionaea seems to be bound to correct IP.

```

```

**Comment by phibos** [comment]
I'm sorry, but at the moment I don't have any experience with running dionaea inside a Kubernetes environment.

Did you get it up and running?

**Comment by Xsenonn** [comment]
Hello, thank you for the response. Sadly I'm still at the point I was when I created this issue. I've managed to run Dionaea as non root user (i hope so) and connect all volumes to the pod. Everything seems to be running, except when I try to send anything to the ports (in my case it was ftp) nothing happens. Dionaea doesn't return any error or success message, the file doesn't appear in any volume I've attached to the pod.

**Comment by Xsenonn** [comment]
[Little Update]
I've re-tried to connect to ftp today, but The connection keeps hanging at "Connected to <IP>.". At this point nothing happens, logs only contain some old entries like those below:
`[09092020 18:04:51] util /root/dionaea/src/util.c:255: could not open path /opt/dionaea/var/dionaea/bistreams/2020-09-09/ (No such file or directory)`
`[09092020 18:04:52] processor /root/dionaea/src/processor.c:393: Could not create /opt/dionaea/var/dionaea/bistreams/2020-09-09/ No such file or directory`
Maybe they are related to this problem.

**Comment by Xsenonn** [comment]
[Update 2]
I've rebuilt docker container to run dionaea as root. No logs are generated. 
Dionaea process inside pod is running, ftp connection returns: 
`ftp: connect to address <POT IP Addr>: Connection refused`
`ftp: no response from host`
And Curl from that IP returns: 
`curl: (7) Failed to connect to 156.17.248.53 port 443: Connection refused`

**Comment by phibos** [comment]
Can you please provide the startup logs from dionaea
- Try to start with ```-l all -L '*'```
- Or from dionaea.log as configured in the config file
```
[logging]
default.filename=@DIONAEA_LOGDIR@/dionaea.log
default.levels=all
default.domains=*
```
