### ISSUE TITLE
Dionaea Honeypot Installation on Centos 7

### ISSUE THREAD

**Issue by sherifoff** [DinoTools/dionaea#286]
Hi, 
I installed dionaea 0.7 honeypot on my Centos. I installed dionaea with package based. I attach status of dionaea honeypot, and also configuration of dionaea. When I run dionaea with workingdir(working directory of honeypot) error show me python.so file is not installed. I think this file will be installed from dionaea. Can you help me for this problem.

![1](https://user-images.githubusercontent.com/24323882/88936170-a9433180-d293-11ea-9c6a-2d0b2600a851.png)
![2](https://user-images.githubusercontent.com/24323882/88936184-ad6f4f00-d293-11ea-83eb-d9aa4658f592.png)
![3](https://user-images.githubusercontent.com/24323882/88936318-d7c10c80-d293-11ea-837d-024afa6a9688.png)

**Comment by sherifoff** [comment]
@DinoTools @katkad @tobiw @rep @gento @xambroz @Aws0mus @mcantoni @tillmannw @justinshenk @Svenito @phibos @christophetd @amerck @262nos can you help me...

**Comment by remyluslosius** [comment]
Hey Sherifoff, I tried to install Dionaea on CentOS 7 a few months ago and it couldn't work because of the missing python.so library. If you check the EPEL repository for the dionaea-0.7.0-5.el.1.x86_64.rpm, you'll see that python.so is missing from the file path. 

Anyway if you're working on your own project and don't mind using Fedora, the dionaea-0.7.0-5.fc30.1.src.rpm works fine with Fedora 31. I haven't tested it Fedora 32.

**Comment by Svenito** [comment]
[this package](https://centos.pkgs.org/7/epel-x86_64/python36-dionaea-0.7.0-1.el7.1.x86_64.rpm.html) provides the `/usr/lib64/dionaea/python.so`

Installing the rpm, or extracting the files at the least, may help your install

**Comment by remyluslosius** [comment]
That's a different rpm than the one I used. it's probably worth giving a try.

**Comment by sherifoff** [comment]
@remyluslosius  I installed Dionaea on ubuntu, after successful installation, how can I emulate ftp, http, smb services?

**Comment by Svenito** [comment]
@sherifoff you will need to setup configs for the services you want to use https://dionaea.readthedocs.io/en/latest/service/index.html In the mainconfig there's a `service_configs=@DIONAEA_CONFDIR@/services-enabled/*.yaml` which tells it what services to enable. The idea is that you create the directory and symlink the service config files into it, and it will load all the ones it finds. 

Doing this from memory, so I might not be 100% correct

**Comment by remyluslosius** [comment]
@sherifoff, Svenito provided you the best possible info you'll need to work with dionaea. If you don't understand certain things in the doc or having issues with any of the steps, just post.

**Comment by sherifoff** [comment]
Thnaks all for you responses.
I installed dionaea on ubuntu 14.04.
In our project we want to emulate ftp, smb, http and ms-sql services.
I configured ftp service emulation, and working on smb service emulation. 
ftp service was success for emulation but still I can not configured smb service(As attached files you can see). 
What do you offer me for smb service emulation? 
![Capture](https://user-images.githubusercontent.com/24323882/89980474-ff947500-dc82-11ea-8fc5-bf6279bb2f0c.JPG)
![z](https://user-images.githubusercontent.com/24323882/89980478-015e3880-dc83-11ea-88e4-d7c38dda10d8.JPG)

**Comment by Svenito** [comment]
Looks to me like you have selected to use Windows XP `os_type: 2` but have configured the smb for Windows 7. Try setting the `os_type` to 4, or alternatively, uncomment the smb at the bottom of the config. See which one works

**Comment by sherifoff** [comment]
I tried  os_type: 4 and uncommented   ## Windows 7 ## side and   ## Samba ## side additionaly, None of attempts worked. What can you offer me...

**Comment by sherifoff** [comment]
Must I add any ihandler from  /ihandlers-avialable/  to /ihandlers-enabled/  ?

**Comment by sherifoff** [comment]
it is not working on centos :(
