### ISSUE TITLE
Dioanea does't want to start

### ISSUE THREAD

**Issue by sarebour** [DinoTools/dionaea#300]
Dionaea Version 0.9.2 
Compiled on Linux/x86_64 at Oct 28 2020 16:40:30 with gcc 8.3.0 
Started on 2e1dc7e5c5e7 running Linux/x86_64 release 4.19.0-12-amd64

dionaea /root/dionaea/src/dionaea.c:756: Setgroups dropping groups failed
python /root/dionaea/modules/python/module.c:1014: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
python /root/dionaea/modules/python/module.c:1039: binding.pyx:749 in None
python /root/dionaea/modules/python/module.c:1040:   dionaea.core._factory

Can somone please tell me what's going on?
Thanks!

**Comment by phibos** [comment]
Please provide additional information.

##### CONFIGURATION

- Do you use the default config?
- Any modifications?

##### OS / ENVIRONMENT

- How did you build the honeypot?
- What is the OS?
- Do you use the docker container?

##### SUMMARY


##### STEPS TO REPRODUCE

You can also add links to gist.github.com.

##### EXPECTED RESULTS


##### ACTUAL RESULTS

- What actually happened? If possible run with increased log level (-l all -L '*')
