### ISSUE TITLE
Swap self-signed certificate for trusted certificate

### ISSUE THREAD

**Issue by Fosocles** [DinoTools/dionaea#305]
Hello!
I want to use a trusted certificate (from Let's Encrypt) instead of the self-signed one Dionaea generates on startup, but cannot find where nor what settings I should change. Can you help me, please?

If this is not supported at the moment, will you consider it as a possible enhancement?
Thanks.

**Comment by phibos** [comment]
Yes it is possible to set a custom certificate and a custom key file. But it looks like this feature hasn't been documented yet. Also it is not possible to provide a certificate chain.

I will fix this in a few days.

**Comment by phibos** [comment]
The issue will be fixed with #309  Feel free to test.

**Comment by phibos** [comment]
Thanks for reporting the issue.

The function has been improved and documented. It will be available in the next release 0.10

**Comment by Fosocles** [comment]
Hi. Thank you for your swift answer and action. Will test it in the following days and report back to you.
