### ISSUE TITLE
Virustotal not registering samples from the honeypot

### ISSUE THREAD

**Issue by izm1chael** [DinoTools/dionaea#316]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
```
Dionaea Version 0.11.0 
Compiled on Linux/x86_64 at Dec 11 2020 22:32:05 with gcc 7.5.0 
Started on dionaea-1 running Linux/x86_64 release 4.15.0-124-generic

```
##### OS / ENVIRONMENT
 - Ubuntu 18.04

I have recently deployed 4 honeypots all on the latest version. 

The issues I am having is that after capturing 40 or so samples I am not seeing anything in virustotal

Can anyone advice as to why this would be the case?

**Comment by phibos** [comment]
Thanks for reporting the issue. Can you please provide some logs. Please enable debug logging if possible.

**Comment by phibos** [comment]
Did you manage to capture the logs? Can you provide some additional information, please.
