### ISSUE TITLE
new column in sqlite database

### ISSUE THREAD

**Issue by aabulaeva** [DinoTools/dionaea#323]
hello again,

i have a trouble, i can't find the database.
i tried to print the different tables:
#!/usr/bin/python

import sqlite3

con = sqlite3.connect(':memory:')
cursor = con. cursor()
cursor. execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor. fetchall())

i need to replace the name of the sha512 column.
can you help me ?
Thanks

**Comment by aabulaeva** [comment]
@phibos please :)

**Comment by phibos** [comment]
You are using an in memory database in your example.
```python
con = sqlite3.connect(':memory:')
```
Please use the database file. By default this should be named ```dionaea.sqlite```
