### ISSUE TITLE
JSON arrays vs. ELK 

### ISSUE THREAD

**Issue by t3chn0m4g3** [DinoTools/dionaea#38]
Just tested JSON logging and it seems Kibana has some issues with (nested) arrays. This example shows a json logging message and since it is easier to read, let's concentrate on the credentials array **at the end**:
```
{"dst_ip": "172.17.0.6", "src_ip": "172.17.0.1", "timestamp": "2016-06-01T20:30:42.655420", "connection": {"transport": "tcp", "protocol": "ftpd", "type": "accept"}, "src_hostname": "", "dst_port": 21, "src_port": 58940, "ftp": {"commands": [{"arguments": ["test"], "command": "USER"}, {"arguments": ["test"], "command": "PASS"}, {"arguments": [], "command": "SYST"}, {"arguments": ["|2|::1|38856|"], "command": "EPRT"}, {"arguments": [], "command": "QUIT"}]}, "credentials": [{"username": "test", "password": "test"}]}
```
In Kibana the credential fields will not be indexed and thus its contents are not accessible for filters / visualizations:
![image](https://cloud.githubusercontent.com/assets/4318452/15725849/12c92f00-284e-11e6-95ad-fa0fee4891d1.png)

The following shows the same message but I flattened the credentials array **at the end** ...
```
{"dst_ip": "172.17.0.6", "src_ip": "172.17.0.1", "timestamp": "2016-06-01T20:30:42.655420", "connection": {"transport": "tcp", "protocol": "ftpd", "type": "accept"}, "src_hostname": "", "dst_port": 21, "src_port": 58940, "ftp": {"commands": [{"arguments": ["test"], "command": "USER"}, {"arguments": ["test"], "command": "PASS"}, {"arguments": [], "command": "SYST"}, {"arguments": ["|2|::1|38856|"], "command": "EPRT"}, {"arguments": [], "command": "QUIT"}]}, "credentials": {"username": "test", "password": "test"}}
```
... which results in proper indexing for Kibana / Elastic and thus allowing for filtering and visualizations:

![image](https://cloud.githubusercontent.com/assets/4318452/15725966/9210d13c-284e-11e6-9a69-746119d6fb93.png)

Can you please flatten out the array structures?

**Comment by phibos** [comment]
You should use the nested type instead of object.
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/nested.html

**Comment by t3chn0m4g3** [comment]
You are right, already thought about it, in regard to how I feed the data this would complicate things, though:
- a custom elastic search template must be provided with all mappings (nested arrays) that might occur
- if changes occurred on the JSON side the template would probably break things (if not adjusted) and in my case, for T-Pot, ELK data resides on the host I had no automatic mechanism to redeploy said changes
- if the index failed or was deleted the mappings template needed to be redeployed manually especially with regard to the Kibana index building up on it and since Kibana 4.x does not support for pre-feeding the mapped fields anymore filters and visualizations would break also

**Comment by phibos** [comment]
I would like to keep the nested structure. But what do you think about an config option like `flat: yes` and dionaea flattens the json before submitting it?

**Comment by t3chn0m4g3** [comment]
Sounds perfect and guarantees a fast switch to nested again once ELK supports it :+1:

**Comment by phibos** [comment]
This issue should be fixed in the next nightly build. Please have a look at the [config example](http://dionaea.readthedocs.io/en/latest/ihandler/log_json.html) on how to enable flat object lists.

**Comment by phibos** [comment]
Closing issue.
