### ISSUE TITLE
Report username and password for ftp service

### ISSUE THREAD

**Issue by phibos** [DinoTools/dionaea#5]
The ftp service doesn't send an incident to report the username and password.

**Comment by t3chn0m4g3** [comment]
Using [tagcloud](https://github.com/stormpython/tagcloud) this could be transformed into a real eye [catcher](https://camo.githubusercontent.com/e23fe1992c8b5b561e47cc9cbdd566edf967ed44/687474703a2f2f692e696d6775722e636f6d2f537850356935362e6a7067) :smiley:
