### ISSUE TITLE
Replace lcfg with yaml

### ISSUE THREAD

**Issue by phibos** [DinoTools/dionaea#6]
In the current version of dionaea the lcfg library is used to parse the config file. But there are some downsides:

* Errors in the config file hard to debug
* Config format only used by dionaea
* Additional work to provide/compile packages for lcfg

Why use yaml:

* Simple format and widely spread
* Split config files (e.g. by service)

**Comment by t3chn0m4g3** [comment]
Awesome idea!

:+1:
