### ISSUE TITLE
Creating directory listings

### ISSUE THREAD

**Issue by sphereict** [DinoTools/dionaea#72]
Hi 

would like to create addditonal directories for an attacker to search the ftp server.

I would also like to create login credentials for bruteforce access adding additional users etc.

Could you please be so kind as to assist in how to go about this 

sincerely.
G

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### DIONAEA VERSION

```

```

##### OS / ENVIRONMENT

 - Ubuntu 14.04
 - Ubuntu 16.04
 - Debian 8.0

##### ACTUAL RESULTS

```

```

**Comment by phibos** [comment]
Hi,

I would appreciate it if you could use the template to create new issues and if you could create one issue per topic.

To add new directories or files just create them in the ftp root directory.

To improve the authentication handling you have to modify the ftp service. Have a look at  `modules/python/dionaea/ftp.py`

Best Regards

**Comment by phibos** [comment]
The issues has been closed because there was no response within the last 18 days. A new issue to add support for credentials to the ftp service has been created. For more information have a look at #76

Feel free to reopen the issue if something is unclear.
