### ISSUE TITLE
Cannot compile on musl lib - missing include in dionaea.c - SOLVED

### ISSUE THREAD

**Issue by vikerian** [DinoTools/dionaea#81]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
"5363bf425bef0692b94ac55b1fd7c9784c6da1f1"
```

```

##### CONFIGURATION
default configuration of alpine linux with devel utils

##### OS / ENVIRONMENT
Linux alpine-devel 4.4.27-0-grsec #1-Alpine SMP Tue Oct 25 08:02:00 GMT 2016 x86_64 Linux

##### STEPS TO REPRODUCE
just try to compile dionaea on alpine linux

##### EXPECTED RESULTS
compilation working

##### ACTUAL RESULTS
In file included from dionaea.c:64:0:
../include/pchild.h:48:50: error: unknown type name 'socklen_t'
 int pchild_sent_bind(int sx, struct sockaddr *s, socklen_t size);

```
#### SOLUTION
Add #include <sys/socket.h> into dionaea.c
```

**Comment by phibos** [comment]
@vikerian I have added the 'include' you have suggested. Can you have a look at #82 and verify if this fixes your issue.
