### ISSUE TITLE
Error when install developement version

### ISSUE THREAD

**Issue by savamarius** [DinoTools/dionaea#9]
#I use this instruction:
git clone https://github.com/dionaea-honeypot/dionaea.git
$ cd dionaea/vagrant
$ vagrant up

But these gives me that error:
```
checking if all required dependencies are installed properly... yes - well done, you read the documentation
checking that generated files are newer than configure... done
configure: creating ./config.status
.in'ig.status: error: cannot find input file: `Makefile
```
I trace error and i found out that is happen on ./configure command from build.sh script. 
Any idea?

**Comment by savamarius** [comment]
#error

**Comment by phibos** [comment]
I'm unable to reproduce the issue. Build works as expected.

Software used:
- Host: Linux
- VirtualBox 5.0.16
- Vagrant 1.8.1
- Ubuntu Box latest Version (20160323.0.0)

**Comment by savamarius** [comment]
I make again the test with the following configuration:

    Host: Linux
    VirtualBox 5.0.16
    Vagrant 1.8.1
    Ubuntu Box latest Version (20160323.0.0) 
 Build works as expected.

My initial configuration was:
    Host:** Windows 10**
    VirtualBox 5.0.16
    Vagrant 1.8.1
    Ubuntu Box latest Version (20160323.0.0) 

The problem if you use windows 10 is still reproductible.

**Comment by phibos** [comment]
Would you like to provide a patch to fix this issue?

**Comment by savamarius** [comment]
It would be very nice if so. Thank you

**Comment by phibos** [comment]
Feel free to open a pull request so I can review and merge your fix.
