### ISSUE TITLE
Unable to download files using FTP service

### ISSUE THREAD

**Issue by alem0lars-yoroi** [DinoTools/dionaea#94]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
Dionaea Version 0.6.0
Compiled on Linux/x86_64 at Mar 21 2017 08:54:43 with gcc 5.4.0 20160609
Started on 54da02c3ccd9 running Linux/x86_64 release 3.13.0-103-generic


Dionaea Version 0.6.0
Compiled on Linux/x86_64 at Mar 21 2017 08:54:43 with gcc 5.4.0 20160609
Started on 54da02c3ccd9 running Linux/x86_64 release 3.13.0-103-generic
```

##### CONFIGURATION

I'm using the default configuration.

##### OS / ENVIRONMENT

 - Ubuntu 14.04

##### SUMMARY

When I try to download a file from the FTP service, it doesn't work, giving `502` errors.

##### STEPS TO REPRODUCE

Passive mode:

```
vagrant@default-ubuntu-1404:~$ ftp -v -p localhost 23021
Connected to localhost.
220 Backup server for the Construct Quarter
Name (localhost:vagrant): a
331 Password required for a.
Password:
230 User logged in, proceed
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> get pippo.txt
local: pippo.txt remote: pippo.txt
502 Command 'EPSV' not implemented
Passive mode refused.
```

Active mode:
```
vagrant@default-ubuntu-1404:~$ ftp -v localhost 23021
Connected to localhost.
220 Backup server for the Construct Quarter
Name (localhost:vagrant): a
331 Password required for a.
Password:
230 User logged in, proceed
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> get pippo.txt
local: pippo.txt remote: pippo.txt
502 Command 'EPRT' not implemented
ftp: bind: Address already in use
ftp>
```

##### EXPECTED RESULTS

File is downloaded.

##### ACTUAL RESULTS

I get errors with both passive and active mode.

----

Also, can you please post a working example of usage of FTP service ?
I didn't manage to get it working.
Thanks

**Comment by phibos** [comment]
Thanks for reporting the issue.

The FTP commands EPRT and EPSV are extended commands and are currently not supported by dionaea. Try to force the IPv4 mode of your ftp client.

```console
$ ftp -v 4 localhost
```

**Comment by phibos** [comment]
No answer within month. Closing the issue. Feel free to reopen ore create new issue.
