### ISSUE TITLE
unable to dionaea

### ISSUE THREAD

**Issue by singhkrmanish** [DinoTools/dionaea#96]
i used this command /opt/dionaea/bin/dionaea -u nobody -g nogroup -c /opt/dionaea/etc/dionaea/dionaea.conf -w /opt/dionaea -p /opt/dionaea/var/dionaea.pid -D to start it, but i know that .conf does not exists. This command use to work for the older version. reff: https://github.com/rep/dionaea.

Kindly tell the command to start this version of the dionaea.
PLZ ASAP

**Comment by phibos** [comment]
I would recommend using the issue template when creating a new issue the next time.

- Run the command without the config file parameter and dionaea will use the default config path

OR

- Use ```-c /opt/dionaea/etc/dionaea/dionaea.cfg```

**Comment by phibos** [comment]
I hope you were able to get dionaea up and running. I have closed the issue. If you have any question feel free to reopen it or create a new issue.
